/**
 * TypeScript interfaces for the wrk2gthr engine ↔ Conclave JSON contract.
 *
 * Generated by hand from docs/JSON-CONTRACT.md (E0a + E0b) in the engine repo.
 * These mirror the documented `--json` command payloads and the `collab watch
 * --json` event feed. Additive (unknown) keys must be ignored per the contract,
 * so every interface is intentionally open to extra fields.
 *
 * The extension speaks client schema version 3 — it CALLS schema-3 commands
 * (`seat pause`/`seat resume`) and schema-2 ones (`run stop`, structured finding
 * file/line, per-seat tier), so it genuinely requires an engine at schema >= 3.
 * It is compatible with an engine iff
 *   engine.minClientSchema <= CLIENT_SCHEMA_VERSION <= engine.schemaVersion.
 * Declaring 3 (not 1) makes an older engine fail provisioning fast with a clear
 * "update wrk2gthr" message, instead of passing startup then failing at runtime
 * the moment the user invokes takeover / stop / a schema-2 read.
 */

/** The client schema version this extension build speaks (min engine schema it needs). */
export const CLIENT_SCHEMA_VERSION = 3;

/** Base stamp present on every read payload and watch line. */
export interface SchemaStamped {
  schemaVersion: number;
}

// ── Error / action envelopes ─────────────────────────────────────────────────

export interface EngineErrorPayload {
  code: string;
  message: string;
  hint: string | null;
}

/** Failure envelope: `{schemaVersion, ok:false, error:{code,message,hint}}`. */
export interface ErrorEnvelope extends SchemaStamped {
  ok: false;
  error: EngineErrorPayload;
}

/** Success action envelope base: `{schemaVersion, ok:true, ...}`. */
export interface ActionSuccess extends SchemaStamped {
  ok: true;
}

// ── Read commands ────────────────────────────────────────────────────────────

/** `collab version --json` */
export interface VersionInfo extends SchemaStamped {
  engineVersion: string;
  minClientSchema: number;
}

export interface RunSummary {
  name: string;
  id: number;
  phase: string;
  status: string;
  spend: number;
  problem?: string;
  active: boolean;
}

/** `collab runs --json` */
export interface RunsResponse extends SchemaStamped {
  runs: RunSummary[];
}

export interface AdapterTier {
  alias: string;
  rung: string;
}

export interface AdapterView {
  name: string;
  tiers: AdapterTier[];
}

/** `collab adapters --json` (schema 3 additive read) — the authoritative list of
 *  seat adapters the engine can actually load from its --adapters-dir. The thin
 *  client uses it to enumerate seat names instead of globbing the engine's dir. */
export interface AdaptersResponse extends SchemaStamped {
  adapters: AdapterView[];
}

export interface SeatRow {
  seat: string;
  status: string;
  headroom: string;
  capped: boolean;
  resetsAt: string | null;
  /** Schema 2 (additive): the seat's most-recent ledger tier, or null. Present on
   *  the `status --json` roster; may be absent on older engines / the run-status
   *  seat rows — read defensively. */
  tier?: string | null;
}

export interface RoutingInfo {
  mode: string;
  effective: string;
}

export interface StatusGate {
  id: number;
  kind: string;
  status: string;
}

/** `collab run status [run] --json` */
export interface RunStatus extends SchemaStamped {
  run: string;
  id: number;
  phase: string;
  status: string;
  /** Schema 2 (additive): the run's absolute `working_dir` (set at run start). */
  workingDir?: string;
  /** Schema 2 (additive): the effective build target (scratch clone the fleet
   *  built in) — persisted when a drive passed `--target`, else null. Lets a client
   *  locate produced code for runs it did NOT drive. */
  target?: string | null;
  epsilon: number;
  problem: string;
  criteria: string;
  routing: RoutingInfo;
  seats: SeatRow[];
  headroom: Array<{ seat: string; headroom: string; capped: boolean; resetsAt: string | null }>;
  gate: StatusGate | null;
}

export interface ReportUnit {
  seq: number;
  title: string;
  difficulty: string;
  tier: string;
  author: string;
  reviewer: string;
  status: string;
  commit: string | null;
  qa: string;
}

export interface QaFinding {
  unitSeq: number;
  verdict: string;
  severity: string;
  reviewer: string;
  claim: string;
  evidence: string;
  /** Schema 2 (additive): structured location parsed at QA time from `evidence`
   *  (fallback `claim`). Both null when the reviewer cited no `path:line`. When
   *  present, PREFER these over re-parsing the prose. */
  file?: string | null;
  line?: number | null;
}

export interface LedgerRow {
  seat: string;
  model: string;
  turns: number;
  inTok: number;
  outTok: number;
  cost: number;
  mode: string;
}

/** `collab report [run] --json` */
export interface Report extends SchemaStamped {
  run: string;
  id: number;
  problem: string;
  phase: string;
  status: string;
  /** Schema 2 (additive): run's working dir + effective build target (or null) —
   *  same semantics as on `run status --json`. */
  workingDir?: string;
  target?: string | null;
  seats: string[];
  units: ReportUnit[];
  qaFindings: QaFinding[];
  ratchet: Array<{ reverted: string; unit: number }>;
  merges: Array<{ kind: string; branch: string; commit: string | null }>;
  validate: Array<{ check: string; seat: string; orchestrator: string; command: string }>;
  orchestratorReverify: "allPass" | "failures" | null;
  ledger: LedgerRow[];
  totalCost: number;
}

export interface PerSeatModel {
  seat: string;
  model: string;
  turns: number;
  cost: number;
  mode: string;
}

export interface RollupRow {
  key: string;
  turns: number;
  cost: number;
  exact: number;
  estimated: number;
}

/** `collab ledger [run] --json` */
export interface Ledger extends SchemaStamped {
  run: string;
  id: number;
  perSeatModel: PerSeatModel[];
  perTier: RollupRow[];
  perPhase: RollupRow[];
  total: number;
  exact: number;
  estimated: number;
  budgetUsd: number | null;
  fracUsed: number | null;
}

/** `collab budget show --json` */
export interface BudgetShow extends SchemaStamped {
  run: string;
  id: number;
  budgetUsd: number | null;
  spent: number;
  fracUsed: number | null;
  headroom: number | null;
  exceeded: boolean;
}

export interface GateCritique {
  ordinal: number;
  severity: string;
  seat: string;
  claim: string;
  evidence: string;
}

export interface GateDetail {
  id: number;
  kind: string;
  status: string;
  plan?: { version: number; seat: string; hash: string; content: string };
  critiques?: GateCritique[];
  revisions?: Array<{ findingOrdinal: number; disposition: string; text: string }>;
  tally?: unknown;
  proposals?: unknown;
  options?: Array<string | { action: string; winner: string }>;
}

/** `collab gate show --json` */
export interface GateShow extends SchemaStamped {
  run: string;
  id: number;
  phase?: string;
  status?: string;
  gate: GateDetail | null;
}

// ── Action command envelopes (success shapes) ────────────────────────────────

export interface RunStartResult extends ActionSuccess {
  run: string;
  id: number;
  phase: string;
  seats: string[];
  domain: string;
  approval: string;
  routing: string;
  budgetUsd: number | null;
}

export interface GateApproveResult extends ActionSuccess {
  gate: number;
  kind: string;
  resolution: string;
  winner: string | null;
}

export interface GateRejectResult extends ActionSuccess {
  gate: number;
  kind: string;
  resolution: string;
  feedback: string;
}

export interface BudgetRaiseResult extends ActionSuccess {
  run: string;
  id: number;
  budgetUsd: number;
  gateCleared: boolean;
  resumed: boolean;
}

/** `collab run stop [run] --json` (new at schema 2) — marks the run terminally
 *  stopped so a later resume never re-drives it. */
export interface RunStopResult extends ActionSuccess {
  run: string;
  /** Terminal status the engine sets — "stopped". */
  status: string;
}

/** `collab seat pause <seat> --run <ref> --json` success (new at schema 3). The
 *  engine SETS the seat's pause flag, WAITS for it to leave `working`, then returns
 *  the authoritative interactive resume spec — `ready:true` guarantees paused+idle,
 *  so the client may auto-run the resume command. */
export interface SeatPauseSuccess extends ActionSuccess {
  seat: string;
  /** Vendor session id the resume attaches to. */
  session: string;
  /** The seat's worktree — the cwd the interactive resume must run in. */
  sessionCwd: string;
  /** Interactive resume binary (e.g. "claude"). */
  resumeCommand: string;
  /** Args for the resume binary (e.g. ["--resume","sess-abc"]). */
  resumeArgs: string[];
  /** Always true on success — the seat is paused AND idle, safe to attach. */
  ready: boolean;
}

/** Failure of a seat action — the engine ATOMIC-FAILS (clears its own pause flag),
 *  so the client needs no cleanup on this path, just surface message + hint. */
export interface SeatActionFailure {
  ok: false;
  error: EngineErrorPayload;
}

/** `collab seat pause` result — success spec OR atomic failure. */
export type SeatPauseResult = SeatPauseSuccess | SeatActionFailure;

/** `collab seat resume <seat> --run <ref> --json` success (new at schema 3) —
 *  clears the pause flag so the orchestrator resumes headless driving. */
export interface SeatResumeSuccess extends ActionSuccess {
  seat: string;
  resumed: boolean;
}

/** `collab seat resume` result — success OR failure envelope. */
export type SeatResumeResult = SeatResumeSuccess | SeatActionFailure;

// ── Watch feed (collab watch --json) — JSONL line types ──────────────────────

export interface WatchSnapshotLine extends SchemaStamped {
  type: "snapshot";
  cursor: number;
  /** Cockpit-shaped projection; nested shapes differ from read commands. */
  state: Record<string, unknown>;
}

export interface WatchEventLine extends SchemaStamped {
  type: "event";
  cursor: number;
  runId: number | null;
  event: {
    type: string;
    seat?: string | null;
    itemId?: number | null;
    runId?: number | null;
    ts?: number;
    payload?: Record<string, unknown>;
  };
}

export interface WatchStreamLine extends SchemaStamped {
  type: "stream";
  runId: number | null;
  seat: string;
  line: string;
}

export interface WatchResetLine extends SchemaStamped {
  type: "reset";
  reason: string;
}

export interface WatchRunsChangedLine extends SchemaStamped {
  type: "runs-changed";
  runs: RunSummary[];
}

export type WatchLine =
  | WatchSnapshotLine
  | WatchEventLine
  | WatchStreamLine
  | WatchResetLine
  | WatchRunsChangedLine;
