/**
 * TypeScript interfaces for the wrk2gthr engine ↔ Conclave JSON contract.
 *
 * Generated by hand from docs/JSON-CONTRACT.md (E0a + E0b) in the engine repo.
 * These mirror the documented `--json` command payloads and the `collab watch
 * --json` event feed. Additive (unknown) keys must be ignored per the contract,
 * so every interface is intentionally open to extra fields.
 *
 * The extension speaks client schema version 1. It is compatible with an engine
 * iff  engine.minClientSchema <= CLIENT_SCHEMA_VERSION <= engine.schemaVersion.
 */

/** The client schema version this extension build speaks. */
export const CLIENT_SCHEMA_VERSION = 1;

/** Base stamp present on every read payload and watch line. */
export interface SchemaStamped {
  schemaVersion: number;
}

// ── Error / action envelopes ─────────────────────────────────────────────────

export interface EngineErrorPayload {
  code: string;
  message: string;
  hint: string | null;
}

/** Failure envelope: `{schemaVersion, ok:false, error:{code,message,hint}}`. */
export interface ErrorEnvelope extends SchemaStamped {
  ok: false;
  error: EngineErrorPayload;
}

/** Success action envelope base: `{schemaVersion, ok:true, ...}`. */
export interface ActionSuccess extends SchemaStamped {
  ok: true;
}

// ── Read commands ────────────────────────────────────────────────────────────

/** `collab version --json` */
export interface VersionInfo extends SchemaStamped {
  engineVersion: string;
  minClientSchema: number;
}

export interface RunSummary {
  name: string;
  id: number;
  phase: string;
  status: string;
  spend: number;
  problem?: string;
  active: boolean;
}

/** `collab runs --json` */
export interface RunsResponse extends SchemaStamped {
  runs: RunSummary[];
}

export interface SeatRow {
  seat: string;
  status: string;
  headroom: string;
  capped: boolean;
  resetsAt: string | null;
}

export interface RoutingInfo {
  mode: string;
  effective: string;
}

export interface StatusGate {
  id: number;
  kind: string;
  status: string;
}

/** `collab run status [run] --json` */
export interface RunStatus extends SchemaStamped {
  run: string;
  id: number;
  phase: string;
  status: string;
  epsilon: number;
  problem: string;
  criteria: string;
  routing: RoutingInfo;
  seats: SeatRow[];
  headroom: Array<{ seat: string; headroom: string; capped: boolean; resetsAt: string | null }>;
  gate: StatusGate | null;
}

export interface ReportUnit {
  seq: number;
  title: string;
  difficulty: string;
  tier: string;
  author: string;
  reviewer: string;
  status: string;
  commit: string | null;
  qa: string;
}

export interface QaFinding {
  unitSeq: number;
  verdict: string;
  severity: string;
  reviewer: string;
  claim: string;
  evidence: string;
}

export interface LedgerRow {
  seat: string;
  model: string;
  turns: number;
  inTok: number;
  outTok: number;
  cost: number;
  mode: string;
}

/** `collab report [run] --json` */
export interface Report extends SchemaStamped {
  run: string;
  id: number;
  problem: string;
  phase: string;
  status: string;
  seats: string[];
  units: ReportUnit[];
  qaFindings: QaFinding[];
  ratchet: Array<{ reverted: string; unit: number }>;
  merges: Array<{ kind: string; branch: string; commit: string | null }>;
  validate: Array<{ check: string; seat: string; orchestrator: string; command: string }>;
  orchestratorReverify: "allPass" | "failures" | null;
  ledger: LedgerRow[];
  totalCost: number;
}

export interface PerSeatModel {
  seat: string;
  model: string;
  turns: number;
  cost: number;
  mode: string;
}

export interface RollupRow {
  key: string;
  turns: number;
  cost: number;
  exact: number;
  estimated: number;
}

/** `collab ledger [run] --json` */
export interface Ledger extends SchemaStamped {
  run: string;
  id: number;
  perSeatModel: PerSeatModel[];
  perTier: RollupRow[];
  perPhase: RollupRow[];
  total: number;
  exact: number;
  estimated: number;
  budgetUsd: number | null;
  fracUsed: number | null;
}

/** `collab budget show --json` */
export interface BudgetShow extends SchemaStamped {
  run: string;
  id: number;
  budgetUsd: number | null;
  spent: number;
  fracUsed: number | null;
  headroom: number | null;
  exceeded: boolean;
}

export interface GateCritique {
  ordinal: number;
  severity: string;
  seat: string;
  claim: string;
  evidence: string;
}

export interface GateDetail {
  id: number;
  kind: string;
  status: string;
  plan?: { version: number; seat: string; hash: string; content: string };
  critiques?: GateCritique[];
  revisions?: Array<{ findingOrdinal: number; disposition: string; text: string }>;
  tally?: unknown;
  proposals?: unknown;
  options?: Array<string | { action: string; winner: string }>;
}

/** `collab gate show --json` */
export interface GateShow extends SchemaStamped {
  run: string;
  id: number;
  phase?: string;
  status?: string;
  gate: GateDetail | null;
}

// ── Action command envelopes (success shapes) ────────────────────────────────

export interface RunStartResult extends ActionSuccess {
  run: string;
  id: number;
  phase: string;
  seats: string[];
  domain: string;
  approval: string;
  routing: string;
  budgetUsd: number | null;
}

export interface GateApproveResult extends ActionSuccess {
  gate: number;
  kind: string;
  resolution: string;
  winner: string | null;
}

export interface GateRejectResult extends ActionSuccess {
  gate: number;
  kind: string;
  resolution: string;
  feedback: string;
}

export interface BudgetRaiseResult extends ActionSuccess {
  run: string;
  id: number;
  budgetUsd: number;
  gateCleared: boolean;
  resumed: boolean;
}

// ── Watch feed (collab watch --json) — JSONL line types ──────────────────────

export interface WatchSnapshotLine extends SchemaStamped {
  type: "snapshot";
  cursor: number;
  /** Cockpit-shaped projection; nested shapes differ from read commands. */
  state: Record<string, unknown>;
}

export interface WatchEventLine extends SchemaStamped {
  type: "event";
  cursor: number;
  runId: number | null;
  event: {
    type: string;
    seat?: string | null;
    itemId?: number | null;
    runId?: number | null;
    ts?: number;
    payload?: Record<string, unknown>;
  };
}

export interface WatchStreamLine extends SchemaStamped {
  type: "stream";
  runId: number | null;
  seat: string;
  line: string;
}

export interface WatchResetLine extends SchemaStamped {
  type: "reset";
  reason: string;
}

export interface WatchRunsChangedLine extends SchemaStamped {
  type: "runs-changed";
  runs: RunSummary[];
}

export type WatchLine =
  | WatchSnapshotLine
  | WatchEventLine
  | WatchStreamLine
  | WatchResetLine
  | WatchRunsChangedLine;
